export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAIL = "SIGNUP_USER_FAIL";

export const VERIFY_OTP = "VERIFY_OTP";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAIL = "VERIFY_OTP_FAIL";

export const SIGNUP_DRIVER = "SIGNUP_DRIVER";
export const SIGNUP_DRIVER_SUCCESS = "SIGNUP_DRIVER_SUCCESS";
export const SIGNUP_DRIVER_FAIL = "SIGNUP_DRIVER_FAIL";

